//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Prg251_Porject_01.apps;
namespace Prg251_Porject_01.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        private DBManager DBManagerDelta = new DBManager();
        private Admin.AdminInternal adminaccount;
        private Student.StudentInternal studentaccount;
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        public Admin.AdminInternal Adminaccount { get => adminaccount; set => adminaccount = value; }
        public Student.StudentInternal Studentaccount { get => studentaccount; set => studentaccount = value; }
        internal DBManager DBManagerDelta1 { get => DBManagerDelta; }
        
    }
}
